packages:
 - 'packages/backend'
 - 'packages/frontend'
 - 'packages/sw'
 - 'packages/cherrypick-js'
 - 'packages/cherrypick-js/generator'
 - 'packages/misskey-reversi'
 - 'packages/misskey-bubble-game'
