name: Publish Docker image (deploy)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false
          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
      - name: Set environment variables
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
          echo "CLIENT_ASSETS_BASE_URL=${{ secrets.CLIENT_ASSETS_BASE_URL }}" >> $GITHUB_ENV
          echo "CLIENT_ASSETS_DIR=$(git show --no-patch --format='%at' HEAD)-$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.ARM_NODE_PORT }} -H ${{ secrets.ARM_NODE_ADDR }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          endpoint: unix:///var/run/docker.sock
          platforms: linux/amd64
          append: |
            - endpoint: ssh://${{ secrets.ARM_NODE_USER }}@${{ secrets.ARM_NODE_ADDR }}:${{ secrets.ARM_NODE_PORT }}
              platforms: linux/arm64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}, ghcr.io/${{ github.repository }}:develop
      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v2
      - name: Install frontend dependencies
        run: |
          git submodule update --init
          NODE_ENV=production pnpm --filter cherrypick-js install
          NODE_ENV=production pnpm --filter frontend install
      - name: Build frontend
        run: |
          sed -i "s/outDir: __dirname + '\/..\/..\/built\/_vite_'/outDir: __dirname + '\/..\/..\/vite'/" packages/frontend/vite.config.ts
          NODE_ENV=production pnpm --filter cherrypick-js build
          NODE_ENV=production pnpm --filter frontend build
          sed -i "s/outDir: __dirname + '\/..\/..\/vite'/outDir: __dirname + '\/..\/..\/built\/_vite_'/" packages/frontend/vite.config.ts
      - name: Deploy frontend
        run: echo "${{ secrets.UPLOAD_SCRIPT }}" | base64 -d | node
      - name: Build and Push to Container registry
        uses: docker/build-push-action@v5
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deploy.Dockerfile
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags: ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}, ghcr.io/${{ github.repository }}:develop
          labels: ${{ env.COMMIT_SHA }}, develop
          build-args: |
            ARGS_CLIENT_ASSETS_BASE_URL=${{ env.CLIENT_ASSETS_BASE_URL }}
            ARGS_CLIENT_ASSETS_DIR=${{ env.CLIENT_ASSETS_DIR }}
